environment:
  matrix:
    - PYTHON: "C:\\PYTHON27"
    - PYTHON: "C:\\PYTHON27-x64"
    - PYTHON: "C:\\PYTHON34"
    - PYTHON: "C:\\PYTHON34-x64"
    - PYTHON: "C:\\PYTHON35"
    - PYTHON: "C:\\PYTHON35-x64"
    - PYTHON: "C:\\PYTHON36"
    - PYTHON: "C:\\PYTHON36-x64"
build: off
test_script:
  - "%PYTHON%\\python.exe ci.py"
artifacts:
  - path: "C:\\projects\\ttk-themes\\dist\\*.whl"
    name: "wheel-windows-%PYTHON%"
