language: python
required: sudo
python:
    - "2.7"
    - "3.5"
    - "3.6"
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    - sudo apt-get install python-tk
    - sudo apt-get install python3-tk
    - sudo apt-get install libtk-img
    - sudo pip install codecov coverage
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then python ttkthemes/setup.py install; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then python3 ttkthemes/setup.py install; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then python3 ttkthemes/setup.py install; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then python tests.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then python3 tests.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then python3 tests.py; fi
after_success:
    - coverage run tests.py
    - codecov
